#!/bin/sh
#
# CGI wrapper for generating barcode image requests
#
# Author: Dan Bornstein, danfuzz@milk.com
# Copyright (c) 1994-2001 Dan Bornstein. All rights reserved.
#
# See the file barcode.c for more details.

cat <<EOF
Content-type: text/html
Cache-Control: max-age=3600

<html><head><title>Your Requested Barcode</title>
</head><body><h1>Your Requested Barcode</h1>
<!-- generated by barcode-request.cgi, part of the milk.com Barcode Server -->
EOF

if [ "x$CONTENT_LENGTH" = 'x' ]; then
    echo "I'm sorry; you don't seem to have filled out the form, or"
    echo "perhaps you tried reloading without reposting form data."
    echo "</body></html>"
    exit 0
fi

if [ "x$CONTENT_TYPE" != 'xapplication/x-www-form-urlencoded' ]; then
    echo "I'm sorry; I don't understand the content type ($CONTENT_TYPE)"
    echo "that your client produces.</body></html>"
    exit 0
fi

read content
pass=`./barcode --print-password`
url="barcode-image.cgi?password=${pass}&${content}"

cat <<EOF
<p><hr></p>
<p><a href="${url}"><img src="${url}"></a></p>
<p><hr></p>

<p><b>Shameless Promotion:</b> If you're the type that likes typing
barcodes into a form to see what they look like, then there's a good
chance that you're also the type of person who likes weird
electronic music. I'd be tickled pink if you wanted to listen to
my stuff.
<a href="http://www.milk.com/fuzzboy/">See this for details.</a></p>

<p>Enjoy!</p>

<p><hr>
The <a href="http://www.milk.com/barcode/">Barcode Server</a><br>
Site copyright &copy; 1994&ndash;2023 Dan Bornstein. All rights reserved.</p>
</body>
</html>
EOF
